### ISSUE TITLE
fzf_key_bindings.fish is a broken link!

### ISSUE THREAD

**Issue by galvanizedheart** [ghostx31/dotfiles#1]
Hi, the fzf_key_bindings.fish file under fish/functions/ is not an executable file, it actually is a link to /home/ghost/yaddayadda..
could you upload the actual file pls? I really like your rice :)

**Comment by ghostx31** [comment]
Hi!
Sorry I've been meaning to delete the file. Must have slipped my mind. I stopped using the fish supplied fzf bindings and instead use [this](https://github.com/jethrokuan/fzf) package installed from fisher for the keybindings. 
But if you want to use the fish's fzf bindings, fish sources its default fzf bindings from `/usr/share/fish/vendor_functions.d/fzf_key_bindings.fish`. You can move this file to your `~` , make the changes you want to and then symlink this file with the one at `~/.config/fish/functions/fzf_key_bindings.fish` or else you can delete this symlink file and fish will source from its default file.

**Comment by ghostx31** [comment]
I guess I can count this as completed. I'll close this for now.
