### ISSUE TITLE
Potential issue in wezterm config

### ISSUE THREAD

**Issue by griimick** [ghostx31/dotfiles#2]
Move the `update-status` event handler out of `format-tab-title` event handler. The current config will lead to increased CPU usage with time. My cooling fans went blower mode after setting this xD

https://github.com/ghostx31/dotfiles/blob/main/private_dot_config/wezterm/wezterm.lua#L124,L145

**Comment by ghostx31** [comment]
Wait so my increased CPU usage was due to this? Lmao I'll fix this 😂
